baseurl = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "blue"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 6

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false


  enableEmoji = true

  # center theme with default width
  centerTheme = true

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false
  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = ""
  site = ""

[languages]
  [languages.en]
    languageName = "English"
    title = "Terminal"
    subtitle = "A simple, retro theme for Hugo"
    owner = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "La oficina de sastroza"
      logoHomeLink = "/posts/myfirst/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "inscripcion"
        name = "Inscripción"
        url = "/inscripcion"
      [[languages.en.menu.main]]
        identifier = "memoria"
        name = "Memoria"
        url = "/memoria"
      [[languages.en.menu.main]]
        identifier = "practica"
        name = "Práctica"
        url = "/practica"
      [[languages.en.menu.main]]
        identifier = "ayuda"
        name = "Ayuda"
        url = "/ayuda"
      [[languages.en.menu.main]]
        identifier = "conexion"
        name = "Conexión"
        url = "/conexion"
      [[languages.en.menu.main]]
        identifier = "elimina"
        name = "Elimina"
        url = "/elimina"